[package]
name = "smart-bench-macro"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
heck = "0.4.0"
subxt-codegen = { git = "https://github.com/paritytech/subxt", branch = "aj-export-typegen" }
ink_metadata = "3.0.0-rc8"
proc-macro2 = "1.0.36"
proc-macro-error = { version = "1.0.4", default-features = false }
serde = "1.0.136"
serde_json = "1.0.78"
syn = "1.0.86"
quote = "1.0.15"
